### ISSUE TITLE
"enums with non-literal initializers not supported" but `-1` is literal

### ISSUE THREAD

**Issue by KAIYOHUGO** [ratchetdesigns/ts-bindgen#26]
Error Code

```js
declare enum A {
    B = -1
}
```

Error from here

https://github.com/ratchetdesigns/ts-bindgen/blob/1e81e05f21967d44c88e9ad1aaecafb80c31b86f/ts-bindgen-gen/src/parse.rs#L2127-L2140

SWC AST

```json
{
  "init": {
    "type": "UnaryExpression",
    "span": {
      "start": 15,
      "end": 17,
      "ctxt": 0
    },
    "operator": "-",
    "argument": {
      "type": "NumericLiteral",
      "span": {
        "start": 16,
        "end": 17,
        "ctxt": 0
      },
      "value": 1,
      "raw": "1"
    }
  }
}
```

**Comment by abrgr** [comment]
Thanks for the report. Will put up a fix for the negative number case.

**Comment by ctron** [comment]
Just ran into this too. Is there a fix available already? The playground still seems to suffer from this issue.
