### ISSUE TITLE
Question regarding maintenance status, and official announcement

### ISSUE THREAD

**Issue by d4h0** [ratchetdesigns/ts-bindgen#28]
Hi,

`ts-bindgen` looks pretty interesting, and therefore I'd like to give it a try ([unfortunately the installation currently fails](https://github.com/ratchetdesigns/ts-bindgen/issues/27)).

I wrote the text below as a “sidenote”, to an issue I wanted to open regarding what is already reported in #27 (which I only noticed after writing my issue). However, I'm still interested in hearing the answers to the questions below.

I'm curious, if this project is still developed, or if it is dead (which would be a pity!). It seems, after the initial release, there wasn't much activity.

If the project is still active: I've noticed (after I specifically looked), that `ts-bindgen` wasn't announced on `r/rust`. I only found an announcement on `r/WebAssembly` (which has a tiny fraction of the user base of `r/rust`).

I'm pretty sure, I'm not the only one in the Rust community who is extremely excited about a tool like `ts-bindgen` (I'm hoping this enables me to write less JavaScript & TypeScript!) — is there a reason, why `ts-bindgen` wasn't announced on `r/rust`?

Maybe this would attract some capable devs who could help improve `ts-bindgen`? 

(Unfortunately, that is probably not me. The TypeScript type system looks pretty insane to me... 😆).

Anyway, it would be great to know if it still makes sense to invest time to play with `ts-bindgen`.

**Comment by abrgr** [comment]
Hi @d4h0 - really glad that you're interested in the project. I have not been able to devote significant time to this recently though I do plan to come back to this. My current work doesn't require rust/ts interop but the next phase will. Regardless, I will try to get the install running soon (certainly open to a PR but will try to get this done one weekend soon).

There is definitely some work to do to get this into a really usable state. I think most importantly, `this` handling in functions and some other invocation marshalling issues need to be addressed.

I am definitely interested in announcing more broadly but wanted to get this to a more usable/useful state beforehand. I'm not against a broader announcement if the demo (https://ts-bindgen.ratchetdesigns.com/) is something you think could drum up some interest.

**Comment by d4h0** [comment]
Thanks for your response, @abrgr!

> My current work doesn't require rust/ts interop but the next phase will.

Do you have a rough estimate when the next phase of the project will start?

I managed to install `ts-bindgen` by cloning the repo, and then executing `cargo update -p scoped-tls --precise 1.0.0` (so reproducing that probably would be an easy fix for the current installation issue).

However, when I run `cargo  run -p ts-bindgen -- --output /tmp/bindings.rs ./node_modules/playwright/index.d.ts`, I get lots of errors like:

`unresolved alias TypeName { file: "/tmp/ts-bindgen/node_modules/playwright-core/types/types.d.ts", name: Name("Readable") }`

And:

`io error: Could not find node_modules directory starting at /tmp/ts-bindgen/node_modules/playwright-core/types`

For my current project I went with another solution (so there is no pressure to fix anything), but `ts-bindgen` would make many things much more ergonomic (which is why I'm still very interested in `ts-bindgen`).

Playwright would probably be a good test subject for `ts-bindgen`... ;)

>  I'm not against a broader announcement if the demo (https://ts-bindgen.ratchetdesigns.com/) is something you think could drum up some interest.

So, if the demo can already be used to generate simple bindings, then I feel an announcement would be appropriated. Making an announcement now, and another later when some of the current issues are fixed would most-likely be better for "marketing".

However, whether an announcement makes sense, basically depends on whether you are able/willing to respond to new issues/PRs/etc. (I wouldn't want to spend too much time one something that I'm not using myself).  

That being said, a month ago there was an [announcement](https://www.reddit.com/r/rust/comments/z1qc6n/1password_releases_typeshare_the_ultimate_tool/) for [TypeShare](https://github.com/1Password/typeshare), which is somewhat related to `ts-bindgen`, which had a ton of engagement. So it seems there is significant interest for tools like `ts-bindgen` (and `ts-bindgen` seems to do much more for TypeScript than alternatives do).

**Comment by abrgr** [comment]
Thanks. I didn't see TypeShare - excited to check it out!

We don't do great resolution of builtin modules yet - there is some work to do there.

I aim to be back working on this in about 6 months but am hoping to get a bit of time to get the basics working again much sooner.

**Comment by d4h0** [comment]
Alright, thanks for answering my questions, @abrgr. I'll definitely keep an eye on `ts-bindgen`!
